- name: My Test vars playbook
  hosts: all
  become: yes
  become_method: sudo

  vars:
    src_dir: ../public_html
    j2_dir: ../public_html_j2
    dst_dir: /var/www/html

  # === ^^vars^^

  tasks:

  - name: Check and print linux version
    debug: var=ansible_os_family

  - block: # Block for RedHat

    - name: Stop firewall
      service: name=firewalld state=stopped enabled=false

    - name: Install Apache Web Server for RedHat
      yum: name=httpd state=latest

    - name: Run Apache Web Server for RedHat
      service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block: # Block for Debian

    - name: Install Apache Web Server for Debian
      apt: name=apache2 state=latest

    - name: Run Apache Web Server for Debian
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  - name: Copy directory recursively
    copy:
        src={{src_dir}}/
        dest={{dst_dir}}/

  - name: Compile templates
    template:
        src={{j2_dir}}/{{item}}
        dest={{dst_dir}}/{{(item|splitext)[0]}}.html
    with_items:
        - index.j2

  - name: Set owner of webserver dir and file
    file:
        path={{dst_dir}}/
        recurse=yes
        owner=apache
        group=apache
    when: ansible_os_family == "RedHat"

  - name: Set owner of webserver dir and file
    file:
        path={{dst_dir}}/
        recurse=yes
        owner=www-data
        group=www-data
    when: ansible_os_family == "Debian"

  # === ^^tasks^^
